import React, { useContext } from "react";
import { GlobalContext } from "../../context/GlobalState";
import { TransactionList } from "../TransactionList";
import { AddTransaction } from "../AddTransaction";
import { TransactionSearch } from "../TransactionSearch";

// [FIX 1] UBAH CARA IMPORT PDF
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable"; // Import sebagai variabel

export const TransactionsPage = () => {
  const { transactions, user } = useContext(GlobalContext);

  const downloadPDF = () => {
    // [FIX 2] PANGGIL DENGAN NEW INSTANCE
    const doc = new jsPDF();

    // Header & Desain (Tetap sama)
    doc.setFillColor(108, 92, 231);
    doc.rect(0, 0, 210, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Smart Finance", 14, 20);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Laporan Keuangan Pribadi", 14, 28);
    doc.text(`Dicetak Oleh: ${user ? user.name : "User"}`, 150, 20);
    doc.text(`Tanggal: ${new Date().toLocaleDateString("id-ID")}`, 150, 28);

    // Ringkasan Saldo (Tetap sama)
    const income = transactions
      .filter((t) => t.amount > 0)
      .reduce((acc, t) => acc + t.amount, 0);
    const expense = transactions
      .filter((t) => t.amount < 0)
      .reduce((acc, t) => acc + t.amount, 0);
    const balance = income + expense;

    doc.setTextColor(45, 52, 54);
    doc.setFontSize(12);
    doc.text(`Saldo Akhir: Rp ${balance.toLocaleString("id-ID")}`, 14, 55);
    doc.setFontSize(10);
    doc.setTextColor(0, 184, 148);
    doc.text(`Total Pemasukan: +Rp ${income.toLocaleString("id-ID")}`, 14, 62);
    doc.setTextColor(214, 48, 49);
    doc.text(
      `Total Pengeluaran: -Rp ${Math.abs(expense).toLocaleString("id-ID")}`,
      80,
      62,
    );

    // [FIX 3] DATA TABEL
    const tableColumn = [
      "Tanggal",
      "Keterangan",
      "Kategori",
      "Tipe",
      "Nominal (Rp)",
    ];
    const tableRows = [];

    transactions.forEach((t) => {
      const transactionData = [
        new Date(t.transactionDate).toLocaleDateString("id-ID"),
        t.text,
        t.category,
        t.amount > 0 ? "Pemasukan" : "Pengeluaran",
        t.amount.toLocaleString("id-ID"),
      ];
      tableRows.push(transactionData);
    });

    // [FIX 4] CARA PANGGIL AUTOTABLE YANG BARU
    // Gunakan fungsi autoTable(doc, options) alih-alih doc.autoTable
    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 70,
      theme: "grid",
      headStyles: { fillColor: [108, 92, 231], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      alternateRowStyles: { fillColor: [240, 242, 245] },
      didParseCell: function (data) {
        if (data.section === "body" && data.column.index === 4) {
          const rawVal = data.cell.raw;
          if (rawVal.includes("-")) {
            data.cell.styles.textColor = [214, 48, 49];
          } else {
            data.cell.styles.textColor = [0, 184, 148];
          }
        }
      },
    });

    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text("Generated by Smart Finance App © 2026", 14, pageHeight - 10);

    doc.save(`Laporan_Keuangan_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  return (
    // ... (TAMPILAN BAWAH TIDAK BERUBAH/SAMA SEPERTI SEBELUMNYA)
    <div className="dashboard-row content-row animate-fade-in">
      <div
        className="history-section"
        style={{ display: "flex", flexDirection: "column" }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: "20px",
            borderBottom: "2px solid var(--border-color)",
            paddingBottom: "15px",
          }}
        >
          <h3 style={{ margin: 0, border: "none", padding: 0 }}>
            Riwayat Transaksi 📜
          </h3>
          <button
            onClick={downloadPDF}
            className="btn"
            style={{
              width: "auto",
              margin: 0,
              padding: "10px 20px",
              fontSize: "0.9rem",
              background: "var(--success)",
              display: "flex",
              alignItems: "center",
              gap: "8px",
            }}
          >
            <i className="fas fa-file-pdf"></i> Download PDF
          </button>
        </div>
        <TransactionSearch />
        <div style={{ flex: 1 }}>
          <TransactionList />
        </div>
      </div>
      <div className="form-section">
        <h3 style={{ marginBottom: "20px" }}>Tambah Baru ➕</h3>
        <AddTransaction />
      </div>
    </div>
  );
};
